# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180513_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'UserInfo员工表', 'verbose_name_plural': 'UserInfo员工表'},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='UserInfo员工表',
        ),
    ]
