# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180513_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': 'ClassList班级表', 'verbose_name_plural': 'ClassList班级表'},
        ),
        migrations.AlterModelOptions(
            name='consultrecord',
            options={'verbose_name': 'ConsultRecord客户跟进记录表', 'verbose_name_plural': 'ConsultRecord客户跟进记录表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course课程表', 'verbose_name_plural': 'Course课程表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': 'CourseRecord上课记录表', 'verbose_name_plural': 'CourseRecord上课记录表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer客户表', 'verbose_name_plural': 'Customer客户表'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department部门表', 'verbose_name_plural': 'Department部门表'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School校区表', 'verbose_name_plural': 'School校区表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student学生表', 'verbose_name_plural': 'Student学生表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': 'StudyRecord学生记录表', 'verbose_name_plural': 'StudyRecord学生记录表'},
        ),
        migrations.AlterModelTable(
            name='classlist',
            table='ClassList班级表',
        ),
        migrations.AlterModelTable(
            name='consultrecord',
            table='ConsultRecord客户跟进记录表',
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course课程表',
        ),
        migrations.AlterModelTable(
            name='courserecord',
            table='CourseRecord上课记录表',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer客户表',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department部门表',
        ),
        migrations.AlterModelTable(
            name='school',
            table='School校区表',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student学生表',
        ),
        migrations.AlterModelTable(
            name='studyrecord',
            table='StudyRecord学生记录表',
        ),
    ]
