# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission_rbac', '0005_auto_20180426_1607'),
        ('app01', '0005_customerdistrbute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='permission_rbac.User'),
        ),
    ]
