# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission_rbac', '0002_auto_20180426_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={'verbose_name': '分组表'},
        ),
        migrations.AlterModelTable(
            name='permissiongroup',
            table='分组表',
        ),
    ]
